### ISSUE TITLE
So, the Serial port expander only works with EZO sensors?

### ISSUE THREAD

**Issue by freeridre** [Atlas-Scientific/Ezo_uart_lib#1]
Because the documentation does not mention it, but the tutorial says that it only works with EZO sensors. 

[HOW-TO-EXPAND-ONE-SERIAL-PORT-INTO-EIGHT](https://www.instructables.com/HOW-TO-EXPAND-ONE-SERIAL-PORT-INTO-EIGHT/)
_Works with the following Atlas Scientific's EZO sensors: pH, salinity, dissolved oxygen (DO), temperature, oxidation-reduction potential (ORP), CO2, peristaltic pump._

So, what's the truth?
Thanks!

**Comment by Atlas-Scientific** [comment]
What other devices do you need it to work with?

**Comment by freeridre** [comment]
hc-05 bluetooth device

**Comment by Atlas-Scientific** [comment]
yea you can probably use the serial multiplexer to switch the line between several EZO sensors and the bluetooth device. We can't know how well every existing device will work with it, so we only guarantee EZO sensors, but generally speaking it can pass through serial data from all kinds of sensors,

**Comment by freeridre** [comment]
> yea you can probably use the serial multiplexer to switch the line between several EZO sensors and the bluetooth device. We can't know how well every existing device will work with it, so we only guarantee EZO sensors, but generally speaking it can pass through serial data from all kinds of sensors,

Yes, I can proof that it worked as expected. Thank you so much! Do you have SPI -to UART expander, so if I’m lack of UART ports I can use SPI instead.

**Comment by Atlas-Scientific** [comment]
We don't sell such a device, nor can we recommend one, but if you find one that works let us know.
